#! /bin/bash
set -e
FILENAME="vault.backup.$(date +%F_%R)"


help () {
  echo "consul-backup"
  echo "Backups consul to a s3 bucket. You must provde all 3 arguments"
  echo
  echo "Usage: consul-backup -h CONSUL_HOST -p CONSUL_PORT -b somebucketname"
  echo
  echo "-h | --host     - The Consul Host"
  echo "-p | --port     - The Consul Port"
  echo "-b | --3bucket  - The s3 bucket path to use, no trailing slash"

}

if [[ $# -ne 6 ]] ; then
    echo 'ERROR: All 3 arguments must be specified'
    help
    exit 1
fi


while [[ $# > 1 ]]
do
key="$1"

case $key in
    -h|--host)
    API_HOST="$2"
    shift
    ;;
    -p|--port)
    API_PORT="$2"
    shift
    ;;
    -b|--s3bucket)
    S3_URL="$2"
    shift
    ;;
    *)
    ;;
esac
shift
done



echo APIHOST = "{$API_HOST}"
echo API_PORT = "{$API_PORT}"
echo S3_URL = "{$S3_URL}"

#Dump Keys
consulate --api-host "$API_HOST" --api-port "$API_PORT" kv backup -b -f "$FILENAME"

#Upload to s3
aws s3 cp "$FILENAME" "$S3_URL/$FILENAME"

#Remove file
rm "$FILENAME"
