#! /bin/bash
set -e

help () {
  echo "consul-backup"
  echo "Backups consul to a s3 bucket. You must provde all 4 arguments"
  echo
  echo "Usage: consul-backup -h CONSUL_HOST -p CONSUL_PORT -b somebucketname"
  echo
  echo "-h | --host     - The Consul Host"
  echo "-p | --port     - The Consul Port"
  echo "-b | --s3bucket  - The s3 bucket path to use, no trailing slash"
  echo "-f | --filename  - The prefix for the filename."
}

if [[ $# -ne 8 ]] ; then
    echo 'ERROR: All 4 arguments must be specified'
    help
    exit 1
fi


while [[ $# > 1 ]]
do
key="$1"

case $key in
    -h|--host)
    API_HOST="$2"
    shift
    ;;
    -p|--port)
    API_PORT="$2"
    shift
    ;;
    -b|--s3bucket)
    S3_URL="$2"
    shift
    ;;
    -f|--filename)
    FILENAME=FILENAME="$2"$(date +%F_%R)
    shift
    ;;
    *)
    ;;
esac
shift
done

echo APIHOST = "{$API_HOST}"
echo API_PORT = "{$API_PORT}"
echo S3_URL = "{$S3_URL}"
echo FILENAME = "{$FILENAME}"

#Dump Keys
consulate --api-host "$API_HOST" --api-port "$API_PORT" kv backup -b -f "$FILENAME"

#Upload to s3
aws s3 cp "$FILENAME" "$S3_URL/$FILENAME"

#Remove file
rm "$FILENAME"
